/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.services;

import io.getstream.models.*;

public class Channel {
  private String channelType;
  private String channelID;
  private Chat service;

  public Channel(String channelType, String channelID, Chat service) {
    this.channelType = channelType;
    this.channelID = channelID;
    this.service = service;
  }

  // Operations

  // Helper templates for parameter signatures and calls in Java
}
