/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ActivityMarkedEvent {

  @JsonProperty("all_read")
  private Boolean allRead;

  @JsonProperty("all_seen")
  private Boolean allSeen;

  @JsonProperty("created_at")
  private Instant createdAt;

  @JsonProperty("feed_id")
  private String feedID;

  @JsonProperty("user_id")
  private String userID;

  @JsonProperty("type")
  private String type;

  @Nullable
  @JsonProperty("marked_read")
  private List<String> markedRead;

  @Nullable
  @JsonProperty("marked_watched")
  private List<String> markedWatched;
}
