/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

/**
 * Provide feedback on an activity Submit feedback for an activity including options to show less,
 * hide, report, or mute the user
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ActivityFeedbackRequest {

  @Nullable
  @JsonProperty("hide")
  private Boolean hide;

  @Nullable
  @JsonProperty("show_less")
  private Boolean showLess;

  @Nullable
  @JsonProperty("show_more")
  private Boolean showMore;

  @Nullable
  @JsonProperty("user_id")
  private String userID;

  @Nullable
  @JsonProperty("user")
  private UserRequest user;
}
