/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AddCommentReactionResponse {

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("comment")
  private CommentResponse comment;

  @JsonProperty("reaction")
  private FeedsReactionResponse reaction;

  @Nullable
  @JsonProperty("notification_created")
  private Boolean notificationCreated;
}
