/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import io.getstream.annotations.Query;
/**
 * Add user group members
 * Adds members to a user group. All user IDs must exist. The operation is all-or-nothing.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor@lombok.AllArgsConstructor

public class AddUserGroupMembersRequest {
    
    @JsonProperty("member_ids")
    private List<String> memberIds;
    
    @Nullable
    @JsonProperty("as_admin")
    private Boolean asAdmin;
    
    @Nullable
    @JsonProperty("team_id")
    private String teamID;

}
