/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AggregatedActivityResponse {

  @JsonProperty("activity_count")
  private Integer activityCount;

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("group")
  private String group;

  @JsonProperty("score")
  private Double score;

  @JsonProperty("updated_at")
  private Date updatedAt;

  @JsonProperty("user_count")
  private Integer userCount;

  @JsonProperty("user_count_truncated")
  private Boolean userCountTruncated;

  @JsonProperty("activities")
  private List<ActivityResponse> activities;

  @Nullable
  @JsonProperty("is_watched")
  private Boolean isWatched;
}
