/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
    
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AITextConfig{

    @Nullable
    @JsonProperty("async")
    private Boolean async;

    @Nullable
    @JsonProperty("enabled")
    private Boolean enabled;

    @Nullable
    @JsonProperty("profile")
    private String profile;

    @Nullable
    @JsonProperty("rules")
    private List<BodyguardRule> rules;

    @Nullable
    @JsonProperty("severity_rules")
    private List<BodyguardSeverityRule> severityRules;
}
