/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AnalyzeTextField {

  @Nullable
  @JsonProperty("action")
  private String action;

  @Nullable
  @JsonProperty("error")
  private String error;

  @Nullable
  @JsonProperty("id")
  private String id;

  @Nullable
  @JsonProperty("language")
  private String language;

  @Nullable
  @JsonProperty("severity")
  private String severity;

  @Nullable
  @JsonProperty("classifications")
  private List<Classification> classifications;
}
