/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
    
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class APNS{

    @JsonProperty("body")
    private String body;

    @JsonProperty("title")
    private String title;

    @Nullable
    @JsonProperty("content-available")
    private Integer contentAvailable;

    @Nullable
    @JsonProperty("mutable-content")
    private Integer mutableContent;

    @Nullable
    @JsonProperty("sound")
    private String sound;

    @Nullable
    @JsonProperty("data")
    private Map<String, Object> data;
}
