/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AppealItemResponse {

  @JsonProperty("appeal_reason")
  private String appealReason;

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("entity_id")
  private String entityID;

  @JsonProperty("entity_type")
  private String entityType;

  @JsonProperty("id")
  private String id;

  @JsonProperty("status")
  private String status;

  @JsonProperty("updated_at")
  private Date updatedAt;

  @Nullable
  @JsonProperty("decision_reason")
  private String decisionReason;

  @Nullable
  @JsonProperty("attachments")
  private List<String> attachments;

  @Nullable
  @JsonProperty("entity_content")
  private ModerationPayload entityContent;

  @Nullable
  @JsonProperty("user")
  private UserResponse user;
}
