/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Audience {

  @JsonProperty("avg_concurrent_viewers")
  private Integer avgConcurrentViewers;

  @JsonProperty("hours_watched")
  private Double hoursWatched;

  @JsonProperty("peak_concurrent_viewers")
  private Integer peakConcurrentViewers;

  @JsonProperty("unique_viewers")
  private Integer uniqueViewers;

  @JsonProperty("viewer_connections")
  private Integer viewerConnections;

  @JsonProperty("concurrency_by_minute")
  private List<ConcurrencyMinute> concurrencyByMinute;

  @Nullable
  @JsonProperty("peak_at")
  private String peakAt;

  @Nullable
  @JsonProperty("ramp_up_min_to_90pct_peak")
  private Integer rampUpMinTo90pctPeak;

  @Nullable
  @JsonProperty("retention_at_90pct_mark")
  private Double retentionAt90pctMark;

  @Nullable
  @JsonProperty("retention_at_midpoint")
  private Double retentionAtMidpoint;

  @Nullable
  @JsonProperty("shape")
  private String shape;
}
