/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AudioSettingsResponse {

  @JsonProperty("access_request_enabled")
  private Boolean accessRequestEnabled;

  @JsonProperty("default_device")
  private String defaultDevice;

  @JsonProperty("hifi_audio_enabled")
  private Boolean hifiAudioEnabled;

  @JsonProperty("mic_default_on")
  private Boolean micDefaultOn;

  @JsonProperty("opus_dtx_enabled")
  private Boolean opusDtxEnabled;

  @JsonProperty("redundant_coding_enabled")
  private Boolean redundantCodingEnabled;

  @JsonProperty("speaker_default_on")
  private Boolean speakerDefaultOn;

  @Nullable
  @JsonProperty("noise_cancellation")
  private NoiseCancellationSettings noiseCancellation;
}
