/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AutomodDetailsResponse {

  @Nullable
  @JsonProperty("action")
  private String action;

  @Nullable
  @JsonProperty("original_message_type")
  private String originalMessageType;

  @Nullable
  @JsonProperty("image_labels")
  private List<String> imageLabels;

  @Nullable
  @JsonProperty("message_details")
  private FlagMessageDetailsResponse messageDetails;

  @Nullable
  @JsonProperty("result")
  private MessageModerationResult result;
}
