/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
    
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class AutomodDetails{

    @Nullable
    @JsonProperty("action")
    private String action;

    @Nullable
    @JsonProperty("original_message_type")
    private String originalMessageType;

    @Nullable
    @JsonProperty("image_labels")
    private List<String> imageLabels;

    @Nullable
    @JsonProperty("message_details")
    private FlagMessageDetails messageDetails;

    @Nullable
    @JsonProperty("result")
    private MessageModerationResult result;
}
