/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class BlockUsersResponse {

  @JsonProperty("blocked_by_user_id")
  private String blockedByUserID;

  @JsonProperty("blocked_user_id")
  private String blockedUserID;

  @JsonProperty("created_at")
  private Instant createdAt;

  @JsonProperty("duration")
  private String duration;
}
