/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class BookmarkDeletedEvent {

  @JsonProperty("created_at")
  private Instant createdAt;

  @JsonProperty("bookmark")
  private BookmarkResponse bookmark;

  @JsonProperty("custom")
  private Map<String, Object> custom;

  @JsonProperty("type")
  private String type;

  @Nullable
  @JsonProperty("received_at")
  private Instant receivedAt;

  @Nullable
  @JsonProperty("user")
  private UserResponseCommonFields user;
}
