/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class BroadcastDailyRollup {

  @JsonProperty("broadcasts")
  private Integer broadcasts;

  @JsonProperty("day")
  private String day;

  @JsonProperty("dead_air_s")
  private Integer deadAirS;

  @JsonProperty("hours_watched")
  private Double hoursWatched;

  @JsonProperty("incident_windows")
  private Integer incidentWindows;

  @JsonProperty("max_peak_concurrent_viewers")
  private Integer maxPeakConcurrentViewers;

  @JsonProperty("note")
  private String note;

  @JsonProperty("schema_version")
  private String schemaVersion;

  @JsonProperty("source_drops")
  private Integer sourceDrops;

  @JsonProperty("unique_viewers_sum")
  private Integer uniqueViewersSum;

  @JsonProperty("top_broadcasts")
  private List<TopBroadcast> topBroadcasts;

  @JsonProperty("poor_viewers_by_cause")
  private PoorByCause poorViewersByCause;
}
