/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class BroadcastDigest {

  @JsonProperty("schema_version")
  private String schemaVersion;

  @JsonProperty("audience")
  private Audience audience;

  @JsonProperty("broadcast")
  private BroadcastInfo broadcast;

  @JsonProperty("coverage")
  private Coverage coverage;

  @JsonProperty("joins")
  private Joins joins;

  @JsonProperty("poor_tail")
  private PoorTail poorTail;

  @JsonProperty("quality")
  private Quality quality;

  @JsonProperty("segments")
  private Segments segments;

  @JsonProperty("source")
  private SourceHealth source;

  @JsonProperty("viewers")
  private ViewerBehavior viewers;
}
