/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CallStatsParticipantCounts {

  @JsonProperty("live_sessions")
  private Integer liveSessions;

  @JsonProperty("participants")
  private Integer participants;

  @JsonProperty("peak_concurrent_sessions")
  private Integer peakConcurrentSessions;

  @JsonProperty("peak_concurrent_users")
  private Integer peakConcurrentUsers;

  @JsonProperty("publishers")
  private Integer publishers;

  @JsonProperty("sessions")
  private Integer sessions;

  @Nullable
  @JsonProperty("total_participant_duration")
  private Integer totalParticipantDuration;
}
