/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CallStatsLocation {

  @Nullable
  @JsonProperty("accuracy_radius_meters")
  private Integer accuracyRadiusMeters;

  @Nullable
  @JsonProperty("city")
  private String city;

  @Nullable
  @JsonProperty("continent")
  private String continent;

  @Nullable
  @JsonProperty("country")
  private String country;

  @Nullable
  @JsonProperty("country_iso_code")
  private String countryIsoCode;

  @Nullable
  @JsonProperty("latitude")
  private Double latitude;

  @Nullable
  @JsonProperty("longitude")
  private Double longitude;

  @Nullable
  @JsonProperty("subdivision")
  private String subdivision;
}
