/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CallParticipantResponse {

  @JsonProperty("joined_at")
  private Date joinedAt;

  @JsonProperty("role")
  private String role;

  @JsonProperty("user_session_id")
  private String userSessionID;

  @JsonProperty("user")
  private UserResponse user;
}
