/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CampaignStatsResponse {

  @JsonProperty("progress")
  private Double progress;

  @JsonProperty("stats_channels_created")
  private Integer statsChannelsCreated;

  @JsonProperty("stats_completed_at")
  private Instant statsCompletedAt;

  @JsonProperty("stats_messages_sent")
  private Integer statsMessagesSent;

  @JsonProperty("stats_started_at")
  private Instant statsStartedAt;

  @JsonProperty("stats_users_read")
  private Integer statsUsersRead;

  @JsonProperty("stats_users_sent")
  private Integer statsUsersSent;
}
