/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CampaignMessageTemplate {

  @JsonProperty("poll_id")
  private String pollID;

  @JsonProperty("searchable")
  private Boolean searchable;

  @JsonProperty("text")
  private String text;

  @JsonProperty("attachments")
  private List<Attachment> attachments;

  @JsonProperty("custom")
  private Map<String, Object> custom;
}
