/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

/**
 * Cancel import v2 task Requests a controlled stop of an import v2 task. Allowed only for tasks in
 * queued or processing state; a processing import stops cleanly on its next progress tick.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
public class CancelImportV2TaskRequest {}
