/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ChannelBatchUpdatedCompletedEvent {

  @JsonProperty("batch_created_at")
  private Date batchCreatedAt;

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("finished_at")
  private Date finishedAt;

  @JsonProperty("operation")
  private String operation;

  @JsonProperty("status")
  private String status;

  @JsonProperty("success_channels_count")
  private Integer successChannelsCount;

  @JsonProperty("task_id")
  private String taskID;

  @JsonProperty("failed_channels")
  private List<FailedChannelUpdates> failedChannels;

  @JsonProperty("custom")
  private Map<String, Object> custom;

  @JsonProperty("type")
  private String type;

  @Nullable
  @JsonProperty("received_at")
  private Date receivedAt;
}
