/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ChannelMemberLookup {

  @JsonProperty("archived")
  private Boolean archived;

  @JsonProperty("banned")
  private Boolean banned;

  @JsonProperty("blocked")
  private Boolean blocked;

  @JsonProperty("hidden")
  private Boolean hidden;

  @JsonProperty("pinned")
  private Boolean pinned;

  @Nullable
  @JsonProperty("archived_at")
  private Date archivedAt;

  @Nullable
  @JsonProperty("ban_expires")
  private Date banExpires;

  @Nullable
  @JsonProperty("pinned_at")
  private Date pinnedAt;
}
