/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ChannelStateResponseFields {

  @JsonProperty("members")
  private List<ChannelMemberResponse> members;

  @JsonProperty("messages")
  private List<MessageResponse> messages;

  @JsonProperty("pinned_messages")
  private List<MessageResponse> pinnedMessages;

  @JsonProperty("threads")
  private List<ThreadStateResponse> threads;

  @Nullable
  @JsonProperty("hidden")
  private Boolean hidden;

  @Nullable
  @JsonProperty("hide_messages_before")
  private Instant hideMessagesBefore;

  @Nullable
  @JsonProperty("watcher_count")
  private Integer watcherCount;

  @Nullable
  @JsonProperty("active_live_locations")
  private List<SharedLocationResponseData> activeLiveLocations;

  @Nullable
  @JsonProperty("pending_messages")
  private List<PendingMessageResponse> pendingMessages;

  @Nullable
  @JsonProperty("read")
  private List<ReadStateResponse> read;

  @Nullable
  @JsonProperty("watchers")
  private List<UserResponse> watchers;

  @Nullable
  @JsonProperty("channel")
  private ChannelResponse channel;

  @Nullable
  @JsonProperty("draft")
  private DraftResponse draft;

  @Nullable
  @JsonProperty("membership")
  private ChannelMemberResponse membership;

  @Nullable
  @JsonProperty("push_preferences")
  private ChannelPushPreferences pushPreferences;
}
