/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
    
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ChannelMemberLookup{

    @JsonProperty("archived")
    private Boolean archived;

    @JsonProperty("banned")
    private Boolean banned;

    @JsonProperty("hidden")
    private Boolean hidden;

    @JsonProperty("pinned")
    private Boolean pinned;

    @Nullable
    @JsonProperty("archived_at")
    private Date archivedAt;

    @Nullable
    @JsonProperty("ban_expires")
    private Date banExpires;

    @Nullable
    @JsonProperty("pinned_at")
    private Date pinnedAt;
}
