/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ChannelExport {

  @Nullable
  @JsonProperty("cid")
  private String cid;

  @Nullable
  @JsonProperty("id")
  private String id;

  @Nullable
  @JsonProperty("messages_since")
  private Date messagesSince;

  @Nullable
  @JsonProperty("messages_until")
  private Date messagesUntil;

  @Nullable
  @JsonProperty("type")
  private String type;
}
