/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ChannelBatchUpdateRequest {

  @JsonProperty("operation")
  private String operation;

  @JsonProperty("filter")
  private Map<String, Object> filter;

  @Nullable
  @JsonProperty("filter_tags_update")
  private List<String> filterTagsUpdate;

  @Nullable
  @JsonProperty("members")
  private List<ChannelBatchMemberRequest> members;

  @Nullable
  @JsonProperty("data")
  private ChannelDataUpdate data;
}
