/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Channel {

  @JsonProperty("auto_translation_language")
  private String autoTranslationLanguage;

  @JsonProperty("cid")
  private String cid;

  @JsonProperty("created_at")
  private Instant createdAt;

  @JsonProperty("disabled")
  private Boolean disabled;

  @JsonProperty("frozen")
  private Boolean frozen;

  @JsonProperty("id")
  private String id;

  @JsonProperty("type")
  private String type;

  @JsonProperty("updated_at")
  private Instant updatedAt;

  @JsonProperty("custom")
  private Map<String, Object> custom;

  @Nullable
  @JsonProperty("auto_translation_enabled")
  private Boolean autoTranslationEnabled;

  @Nullable
  @JsonProperty("cooldown")
  private Integer cooldown;

  @Nullable
  @JsonProperty("deleted_at")
  private Instant deletedAt;

  @Nullable
  @JsonProperty("last_campaigns")
  private String lastCampaigns;

  @Nullable
  @JsonProperty("last_message_at")
  private Instant lastMessageAt;

  @Nullable
  @JsonProperty("member_count")
  private Integer memberCount;

  @Nullable
  @JsonProperty("message_count")
  private Integer messageCount;

  @Nullable
  @JsonProperty("message_count_updated_at")
  private Instant messageCountUpdatedAt;

  @Nullable
  @JsonProperty("team")
  private String team;

  @Nullable
  @JsonProperty("active_live_locations")
  private List<SharedLocation> activeLiveLocations;

  @Nullable
  @JsonProperty("filter_tags")
  private List<String> filterTags;

  @Nullable
  @JsonProperty("invites")
  private List<ChannelMember> invites;

  @Nullable
  @JsonProperty("members")
  private List<ChannelMember> members;

  @Nullable
  @JsonProperty("config")
  private ChannelConfig config;

  @Nullable
  @JsonProperty("config_overrides")
  private ConfigOverrides configOverrides;

  @Nullable
  @JsonProperty("created_by")
  private User createdBy;

  @Nullable
  @JsonProperty("members_lookup")
  private Map<String, ChannelMemberLookup> membersLookup;

  @Nullable
  @JsonProperty("truncated_by")
  private User truncatedBy;
}
