/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ChatPreferences {

  @Nullable
  @JsonProperty("channel_mentions")
  private String channelMentions;

  @Nullable
  @JsonProperty("default_preference")
  private String defaultPreference;

  @Nullable
  @JsonProperty("direct_mentions")
  private String directMentions;

  @Nullable
  @JsonProperty("distinct_channel_messages")
  private String distinctChannelMessages;

  @Nullable
  @JsonProperty("group_mentions")
  private String groupMentions;

  @Nullable
  @JsonProperty("here_mentions")
  private String hereMentions;

  @Nullable
  @JsonProperty("role_mentions")
  private String roleMentions;

  @Nullable
  @JsonProperty("thread_replies")
  private String threadReplies;
}
