/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CheckResponse {

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("recommended_action")
  private String recommendedAction;

  @JsonProperty("status")
  private String status;

  @Nullable
  @JsonProperty("intent_matched_topic")
  private String intentMatchedTopic;

  @Nullable
  @JsonProperty("intent_score")
  private Double intentScore;

  @Nullable
  @JsonProperty("intent_score_threshold")
  private Double intentScoreThreshold;

  @Nullable
  @JsonProperty("intent_would_fire")
  private Boolean intentWouldFire;

  @Nullable
  @JsonProperty("task_id")
  private String taskID;

  @Nullable
  @JsonProperty("triggered_rules")
  private List<TriggeredRuleResponse> triggeredRules;

  @Nullable
  @JsonProperty("item")
  private ReviewQueueItemResponse item;

  /**
   * @deprecated
   */
  @Deprecated
  @Nullable
  @JsonProperty("triggered_rule")
  private TriggeredRuleResponse triggeredRule;
}
