/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * Create policy test set Save a labeled set of messages that can be re-run against the moderation
 * policy.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CreatePolicyTestSetRequest {

  @JsonProperty("name")
  private String name;

  @Nullable
  @JsonProperty("config_key")
  private String configKey;

  @Nullable
  @JsonProperty("mode")
  private String mode;

  @Nullable
  @JsonProperty("team")
  private String team;

  @Nullable
  @JsonProperty("rows")
  private List<PolicyTestRow> rows;

  @Nullable
  @JsonProperty("seed")
  private PolicyTestSeedSpec seed;
}
