/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/** Create multiple feeds at once Create multiple feeds at once for a given feed group */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CreateFeedsBatchRequest {

  @JsonProperty("feeds")
  private List<FeedRequest> feeds;

  @Nullable
  @JsonProperty("enrich_own_fields")
  private Boolean enrichOwnFields;
}
