/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CreateImportV2TaskResponse {

  @JsonProperty("app_pk")
  private Integer appPk;

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("id")
  private String id;

  @JsonProperty("product")
  private String product;

  @JsonProperty("state")
  private Integer state;

  @JsonProperty("updated_at")
  private Date updatedAt;

  @JsonProperty("settings")
  private ImportV2TaskSettings settings;
}
