/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

/** Create segment Create a segment */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CreateSegmentRequest {

  @JsonProperty("type")
  private String type;

  @Nullable
  @JsonProperty("all_sender_channels")
  private Boolean allSenderChannels;

  @Nullable
  @JsonProperty("all_users")
  private Boolean allUsers;

  @Nullable
  @JsonProperty("description")
  private String description;

  @Nullable
  @JsonProperty("id")
  private String id;

  @Nullable
  @JsonProperty("name")
  private String name;

  @Nullable
  @JsonProperty("filter")
  private Map<String, Object> filter;
}
