/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * Create block list Creates a new application blocklist, once created the blocklist can be used by
 * any channel type
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CreateBlockListRequest {

  @JsonProperty("name")
  private String name;

  @JsonProperty("words")
  private List<String> words;

  @Nullable
  @JsonProperty("is_confusable_folding_enabled")
  private Boolean isConfusableFoldingEnabled;

  @Nullable
  @JsonProperty("is_leet_check_enabled")
  private Boolean isLeetCheckEnabled;

  @Nullable
  @JsonProperty("is_plural_check_enabled")
  private Boolean isPluralCheckEnabled;

  @Nullable
  @JsonProperty("is_substring_matching_enabled")
  private Boolean isSubstringMatchingEnabled;

  @Nullable
  @JsonProperty("team")
  private String team;

  @Nullable
  @JsonProperty("type")
  private String type;

  @Nullable
  @JsonProperty("user_id")
  private String userID;

  @Nullable
  @JsonProperty("user")
  private UserRequest user;
}
