/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * Create a new feed view Create a custom view for a feed group with specific selectors, ranking, or
 * aggregation options
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class CreateFeedViewRequest {

  @JsonProperty("id")
  private String id;

  @Nullable
  @JsonProperty("activity_selectors")
  private List<ActivitySelectorConfig> activitySelectors;

  @Nullable
  @JsonProperty("aggregation")
  private AggregationConfig aggregation;

  @Nullable
  @JsonProperty("ranking")
  private RankingConfig ranking;
}
