/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class DailyDigestCallSessionSummary {

  @JsonProperty("call_cid")
  private String callCid;

  @JsonProperty("call_session_id")
  private String callSessionID;

  @JsonProperty("has_digest")
  private Boolean hasDigest;

  @JsonProperty("counts")
  private CallStatsParticipantCounts counts;

  @Nullable
  @JsonProperty("digest_error")
  private String digestError;

  @Nullable
  @JsonProperty("session_ended_at")
  private String sessionEndedAt;

  @Nullable
  @JsonProperty("session_started_at")
  private String sessionStartedAt;
}
