/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

/**
 * Configuration for deleting all of a user&#39;s chat messages without banning them or deleting
 * their account
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class DeleteUserMessagesRequestPayload {

  @JsonProperty("delete_messages")
  private String deleteMessages;

  @Nullable
  @JsonProperty("channel_cid")
  private String channelCid;

  @Nullable
  @JsonProperty("delete_reactions")
  private Boolean deleteReactions;

  @Nullable
  @JsonProperty("entity_id")
  private String entityID;

  @Nullable
  @JsonProperty("entity_type")
  private String entityType;

  @Nullable
  @JsonProperty("reason")
  private String reason;
}
