/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

/**
 * Delete a push provider Delete a push provider from v2 with multi bundle/package support. v1
 * isn&#39;t supported in this endpoint
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
public class DeletePushProviderRequest {}
