/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.getstream.annotations.Query;

/** Delete message Deletes message Sends events: - message.deleted - message.deleted */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class DeleteMessageRequest {

  @Query("hard")
  @JsonIgnore
  private Boolean Hard;

  @Query("deleted_by")
  @JsonIgnore
  private String DeletedBy;

  @Query("delete_for_me")
  @JsonIgnore
  private Boolean DeleteForMe;
}
