/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class DeleteFeedUserDataResponse {

  @JsonProperty("deleted_activities")
  private Integer deletedActivities;

  @JsonProperty("deleted_bookmarks")
  private Integer deletedBookmarks;

  @JsonProperty("deleted_comments")
  private Integer deletedComments;

  @JsonProperty("deleted_reactions")
  private Integer deletedReactions;

  @JsonProperty("duration")
  private String duration;
}
