/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * Delete Users Deletes users and optionally all their belongings asynchronously. Sends events: -
 * channel.deleted - user.deleted
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class DeleteUsersRequest {

  @JsonProperty("user_ids")
  private List<String> userIds;

  @Nullable
  @JsonProperty("calls")
  private String calls;

  @Nullable
  @JsonProperty("conversations")
  private String conversations;

  @Nullable
  @JsonProperty("files")
  private Boolean files;

  @Nullable
  @JsonProperty("messages")
  private String messages;

  @Nullable
  @JsonProperty("new_call_owner_id")
  private String newCallOwnerID;

  @Nullable
  @JsonProperty("new_channel_owner_id")
  private String newChannelOwnerID;

  @Nullable
  @JsonProperty("user")
  private String user;
}
