/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ExportUserResponse {

  @JsonProperty("duration")
  private String duration;

  @Nullable
  @JsonProperty("messages")
  private List<MessageResponse> messages;

  @Nullable
  @JsonProperty("reactions")
  private List<ReactionResponse> reactions;

  @Nullable
  @JsonProperty("user")
  private UserResponse user;
}
