/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

/**
 * Export user Exports the user&#39;s profile, reactions and messages. Raises an error if a user has
 * more than 10k messages or reactions
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
public class ExportUserRequest {}
