/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class FeedMemberResponse {

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("role")
  private String role;

  @JsonProperty("status")
  private String status;

  @JsonProperty("updated_at")
  private Date updatedAt;

  @JsonProperty("user")
  private UserResponse user;

  @Nullable
  @JsonProperty("invite_accepted_at")
  private Date inviteAcceptedAt;

  @Nullable
  @JsonProperty("invite_rejected_at")
  private Date inviteRejectedAt;

  @Nullable
  @JsonProperty("custom")
  private Map<String, Object> custom;

  @Nullable
  @JsonProperty("membership_level")
  private MembershipLevelResponse membershipLevel;
}
