/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class FeedGroup {

  @JsonProperty("AggregationVersion")
  private Integer aggregationVersion;

  @JsonProperty("AppPK")
  private Integer appPK;

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("DefaultVisibility")
  private String defaultVisibility;

  @JsonProperty("ID")
  private String iD;

  @JsonProperty("updated_at")
  private Date updatedAt;

  @JsonProperty("ActivityProcessors")
  private List<ActivityProcessorConfig> activityProcessors;

  @JsonProperty("ActivitySelectors")
  private List<ActivitySelectorConfig> activitySelectors;

  @JsonProperty("Custom")
  private Map<String, Object> custom;

  @Nullable
  @JsonProperty("DeletedAt")
  private Date deletedAt;

  @Nullable
  @JsonProperty("LastFeedGetAt")
  private Date lastFeedGetAt;

  @Nullable
  @JsonProperty("Aggregation")
  private AggregationConfig aggregation;

  @Nullable
  @JsonProperty("Notification")
  private NotificationConfig notification;

  @Nullable
  @JsonProperty("Ranking")
  private RankingConfig ranking;

  @Nullable
  @JsonProperty("Stories")
  private StoriesConfig stories;
}
