/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * Create multiple follows at once Creates multiple follows at once and broadcasts FollowAddedEvent
 * for each follow
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class FollowBatchRequest {

  @JsonProperty("follows")
  private List<FollowRequest> follows;

  @Nullable
  @JsonProperty("enrich_own_fields")
  private Boolean enrichOwnFields;
}
