/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class GetCallSessionParticipantStatsDetailsResponse {

  @JsonProperty("call_id")
  private String callID;

  @JsonProperty("call_session_id")
  private String callSessionID;

  @JsonProperty("call_type")
  private String callType;

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("user_id")
  private String userID;

  @JsonProperty("user_session_id")
  private String userSessionID;

  @Nullable
  @JsonProperty("publisher")
  private ParticipantSeriesPublisherStats publisher;

  @Nullable
  @JsonProperty("subscriber")
  private ParticipantSeriesSubscriberStats subscriber;

  @Nullable
  @JsonProperty("timeframe")
  private ParticipantSeriesTimeframe timeframe;

  @Nullable
  @JsonProperty("user")
  private ParticipantSeriesUserStats user;
}
