/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/** Basic response information */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class GetDailyDigestResponse {

  @JsonProperty("date")
  private String date;

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("status")
  private String status;

  @Nullable
  @JsonProperty("generated_at")
  private String generatedAt;

  @Nullable
  @JsonProperty("retry_after")
  private Integer retryAfter;

  @Nullable
  @JsonProperty("revision")
  private Integer revision;

  @Nullable
  @JsonProperty("schema_version")
  private String schemaVersion;

  @Nullable
  @JsonProperty("broadcasts")
  private List<BroadcastDigest> broadcasts;

  @Nullable
  @JsonProperty("call_sessions")
  private List<DailyDigestCallSessionSummary> callSessions;

  @Nullable
  @JsonProperty("digest_kinds")
  private List<String> digestKinds;

  @Nullable
  @JsonProperty("broadcast_rollup")
  private BroadcastDailyRollup broadcastRollup;
}
