/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

/** Get Edges Returns the list of all edges available for video calls. */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
public class GetEdgesRequest {}
