/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.getstream.annotations.Query;

/**
 * Get Feeds Rate Limits Retrieve current rate limit status for feeds operations. Returns
 * information about limits, usage, and remaining quota for various feed operations.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class GetFeedsRateLimitsRequest {

  @Query("endpoints")
  @JsonIgnore
  private String Endpoints;

  @Query("android")
  @JsonIgnore
  private Boolean Android;

  @Query("ios")
  @JsonIgnore
  private Boolean Ios;

  @Query("web")
  @JsonIgnore
  private Boolean Web;

  @Query("server_side")
  @JsonIgnore
  private Boolean ServerSide;
}
