/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class GetOrCreateCallResponse {

  @JsonProperty("created")
  private Boolean created;

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("members")
  private List<MemberResponse> members;

  @JsonProperty("own_capabilities")
  private List<OwnCapability> ownCapabilities;

  @JsonProperty("call")
  private CallResponse call;
}
