/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Upsert multiple follows at once Creates or updates multiple follows at once. Does not return an
 * error if follows already exist. Broadcasts FollowAddedEvent only for newly created follows.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class GetOrCreateFollowsRequest {

  @JsonProperty("follows")
  private List<FollowRequest> follows;
}
