/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.getstream.annotations.Query;
import java.util.List;

/**
 * Get predefined filters Get all predefined filters with optional sorting by created_at,
 * updated_at, name, or operation
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class GetPredefinedFiltersRequest {

  @Query("include_stats")
  @JsonIgnore
  private Boolean IncludeStats;

  @Query("sort")
  @JsonIgnore
  private List<SortParamRequest> Sort;
}
