/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/** HLSSettings is the payload for HLS settings */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class HLSSettingsResponse {

  @JsonProperty("auto_on")
  private Boolean autoOn;

  @JsonProperty("enabled")
  private Boolean enabled;

  @JsonProperty("quality_tracks")
  private List<String> qualityTracks;

  @JsonProperty("layout")
  private LayoutSettingsResponse layout;
}
