/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * Import block list items Enqueues an asynchronous bulk import of items into an existing blocklist.
 * Returns a task ID that can be polled via GET /tasks/{id} to observe progress. AddItems is
 * idempotent: items already present are skipped without error. For lists exceeding the HTTP
 * request-body cap, issue repeated import calls each carrying a bounded slice of items — the task
 * result accumulates correctly.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ImportBlockListRequest {

  @JsonProperty("items")
  private List<String> items;

  @Nullable
  @JsonProperty("chunk_size")
  private Integer chunkSize;
}
