/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class IntentTopicRequest {

  @JsonProperty("label")
  private String label;

  @Nullable
  @JsonProperty("analysis_cooldown_seconds")
  private Integer analysisCooldownSeconds;

  @Nullable
  @JsonProperty("description")
  private String description;

  @Nullable
  @JsonProperty("enabled")
  private Boolean enabled;

  @Nullable
  @JsonProperty("max_captured_items")
  private Integer maxCapturedItems;

  @Nullable
  @JsonProperty("refire_cooldown_seconds")
  private Integer refireCooldownSeconds;

  @Nullable
  @JsonProperty("score_threshold")
  private Double scoreThreshold;
}
