/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * An interest tag of a user with its ranking weight and, for computed tags, how many distinct
 * reacted-to activities carried it
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class InterestTagResponse {

  @JsonProperty("count")
  private Integer count;

  @JsonProperty("source")
  private String source;

  @JsonProperty("tag")
  private String tag;

  @JsonProperty("weight")
  private Double weight;
}
