/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Joins {

  @JsonProperty("reason")
  private String reason;

  @JsonProperty("disconnect_reasons")
  private Map<String, Integer> disconnectReasons;

  @JsonProperty("failure_stages")
  private Map<String, Integer> failureStages;

  @Nullable
  @JsonProperty("join_attempts")
  private Integer joinAttempts;

  @Nullable
  @JsonProperty("join_success_rate")
  private Double joinSuccessRate;
}
