/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

/** Labels Run moderation on text and return labels */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class LabelsRequest {

  @JsonProperty("content")
  private String content;

  @Nullable
  @JsonProperty("category")
  private String category;

  @Nullable
  @JsonProperty("content_id")
  private String contentID;

  @Nullable
  @JsonProperty("content_type")
  private String contentType;

  @Nullable
  @JsonProperty("policy")
  private String policy;

  @Nullable
  @JsonProperty("user_id")
  private String userID;
}
