/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
    
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class LimitsSettingsResponse{

    @JsonProperty("max_participants_exclude_roles")
    private List<String> maxParticipantsExcludeRoles;

    @Nullable
    @JsonProperty("max_duration_seconds")
    private Integer maxDurationSeconds;

    @Nullable
    @JsonProperty("max_participants")
    private Integer maxParticipants;

    @Nullable
    @JsonProperty("max_participants_exclude_owner")
    private Boolean maxParticipantsExcludeOwner;
}
