/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/**
 * Mark activities as read/seen/watched Mark activities as read/seen/watched. Can mark by timestamp
 * (seen), activity IDs (read), or all as read.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class MarkActivityRequest {

  @Nullable
  @JsonProperty("mark_all_read")
  private Boolean markAllRead;

  @Nullable
  @JsonProperty("mark_all_seen")
  private Boolean markAllSeen;

  @Nullable
  @JsonProperty("user_id")
  private String userID;

  @Nullable
  @JsonProperty("mark_read")
  private List<String> markRead;

  @Nullable
  @JsonProperty("mark_seen")
  private List<String> markSeen;

  @Nullable
  @JsonProperty("mark_watched")
  private List<String> markWatched;

  @Nullable
  @JsonProperty("user")
  private UserRequest user;
}
