/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
    
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class MessageChangeSet{

    @JsonProperty("attachments")
    private Boolean attachments;

    @JsonProperty("custom")
    private Boolean custom;

    @JsonProperty("html")
    private Boolean html;

    @JsonProperty("mentioned_user_ids")
    private Boolean mentionedUserIds;

    @JsonProperty("mml")
    private Boolean mml;

    @JsonProperty("pin")
    private Boolean pin;

    @JsonProperty("quoted_message_id")
    private Boolean quotedMessageID;

    @JsonProperty("silent")
    private Boolean silent;

    @JsonProperty("text")
    private Boolean text;
}
