/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class MetricsPct {

  @Nullable
  @JsonProperty("freezes")
  private Double freezes;

  @Nullable
  @JsonProperty("geo")
  private Double geo;

  @Nullable
  @JsonProperty("jitter")
  private Double jitter;

  @Nullable
  @JsonProperty("latency")
  private Double latency;

  @Nullable
  @JsonProperty("quality_score")
  private Double qualityScore;
}
