/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ModerationDashboardPreferences {

  @Nullable
  @JsonProperty("disable_flagging_reviewed_entity")
  private Boolean disableFlaggingReviewedEntity;

  @Nullable
  @JsonProperty("flag_user_on_flagged_content")
  private Boolean flagUserOnFlaggedContent;

  @Nullable
  @JsonProperty("media_queue_blur_enabled")
  private Boolean mediaQueueBlurEnabled;
}
