/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import io.getstream.annotations.Query;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor@lombok.AllArgsConstructor

public class MuteUsersRequest {
    
    @Nullable
    @JsonProperty("audio")
    private Boolean audio;
    
    @Nullable
    @JsonProperty("mute_all_users")
    private Boolean muteAllUsers;
    
    @Nullable
    @JsonProperty("muted_by_id")
    private String mutedByID;
    
    @Nullable
    @JsonProperty("screenshare")
    private Boolean screenshare;
    
    @Nullable
    @JsonProperty("screenshare_audio")
    private Boolean screenshareAudio;
    
    @Nullable
    @JsonProperty("video")
    private Boolean video;
    
    @Nullable
    @JsonProperty("user_ids")
    private List<String> userIds;
    
    @Nullable
    @JsonProperty("muted_by")
    private UserRequest mutedBy;

}
