/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class NotificationStatusResponse {

  @JsonProperty("unread")
  private Integer unread;

  @JsonProperty("unseen")
  private Integer unseen;

  @Nullable
  @JsonProperty("last_read_at")
  private Instant lastReadAt;

  @Nullable
  @JsonProperty("last_seen_at")
  private Instant lastSeenAt;

  @Nullable
  @JsonProperty("read_activities")
  private List<String> readActivities;

  @Nullable
  @JsonProperty("seen_activities")
  private List<String> seenActivities;
}
