/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class PolicyTestRun {

  @JsonProperty("config_key")
  private String configKey;

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("id")
  private String id;

  @JsonProperty("rows_completed")
  private Integer rowsCompleted;

  @JsonProperty("rows_total")
  private Integer rowsTotal;

  @JsonProperty("set_id")
  private String setID;

  @JsonProperty("status")
  private String status;

  @JsonProperty("task_id")
  private String taskID;

  @JsonProperty("triggered_by")
  private String triggeredBy;

  @Nullable
  @JsonProperty("completed_at")
  private Date completedAt;

  @Nullable
  @JsonProperty("config_updated_at")
  private Date configUpdatedAt;

  @Nullable
  @JsonProperty("error_message")
  private String errorMessage;

  @Nullable
  @JsonProperty("started_at")
  private Date startedAt;

  @Nullable
  @JsonProperty("metrics")
  private PolicyTestRunMetrics metrics;
}
