/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class PublishedTrackFlags {

  @JsonProperty("audio")
  private Boolean audio;

  @JsonProperty("screenshare")
  private Boolean screenshare;

  @JsonProperty("screenshare_audio")
  private Boolean screenshareAudio;

  @JsonProperty("video")
  private Boolean video;
}
