/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class PublisherVideoMetrics {

  @Nullable
  @JsonProperty("bitrate")
  private ActiveCallsBitrateStats bitrate;

  @Nullable
  @JsonProperty("fps_30")
  private ActiveCallsFPSStats fps30;

  @Nullable
  @JsonProperty("frame_encoding_time_ms")
  private ActiveCallsLatencyStats frameEncodingTimeMs;

  @Nullable
  @JsonProperty("jitter_ms")
  private ActiveCallsLatencyStats jitterMs;

  @Nullable
  @JsonProperty("resolution")
  private ActiveCallsResolutionStats resolution;
}
