/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class PushTemplate {

  @JsonProperty("created_at")
  private Date createdAt;

  @JsonProperty("enable_push")
  private Boolean enablePush;

  @JsonProperty("event_type")
  private String eventType;

  @JsonProperty("updated_at")
  private Date updatedAt;

  @Nullable
  @JsonProperty("template")
  private String template;
}
