/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Quality {

  @JsonProperty("viewer_interruption_note")
  private String viewerInterruptionNote;

  @JsonProperty("interruption_incidents")
  private List<Incident> interruptionIncidents;

  @JsonProperty("connection_avg_jitter_ms")
  private Percentiles connectionAvgJitterMs;

  @JsonProperty("connection_avg_latency_ms")
  private Percentiles connectionAvgLatencyMs;

  @JsonProperty("score_bands_by_connection_pct")
  private ScoreBands scoreBandsByConnectionPct;

  @JsonProperty("score_bands_by_watch_time_pct")
  private ScoreBands scoreBandsByWatchTimePct;

  @Nullable
  @JsonProperty("p50_quality_score")
  private Double p50QualityScore;

  @Nullable
  @JsonProperty("p5_quality_score")
  private Double p5QualityScore;

  @Nullable
  @JsonProperty("viewer_interruption_rate_pct")
  private Double viewerInterruptionRatePct;
}
