/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import io.getstream.annotations.Query;
import java.util.List;
import java.util.Map;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class QueryCallSessionParticipantStatsRequest {

  @Query("limit")
  @JsonIgnore
  private Integer Limit;

  @Query("prev")
  @JsonIgnore
  private String Prev;

  @Query("next")
  @JsonIgnore
  private String Next;

  @Query("sort")
  @JsonIgnore
  private List<SortParamRequest> Sort;

  @Query("filter_conditions")
  @JsonIgnore
  private Map<String, Object> FilterConditions;
}
