/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

/** Basic response information */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class QueryCallParticipantSessionsResponse {

  @JsonProperty("call_id")
  private String callID;

  @JsonProperty("call_session_id")
  private String callSessionID;

  @JsonProperty("call_type")
  private String callType;

  @JsonProperty("duration")
  private Integer duration;

  @JsonProperty("total_participant_duration")
  private Integer totalParticipantDuration;

  @JsonProperty("total_participant_sessions")
  private Integer totalParticipantSessions;

  @JsonProperty("participants_sessions")
  private List<ParticipantSessionDetails> participantsSessions;

  @Nullable
  @JsonProperty("next")
  private String next;

  @Nullable
  @JsonProperty("prev")
  private String prev;

  @Nullable
  @JsonProperty("session")
  private CallSessionResponse session;
}
