/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ReadStateResponse {

  @JsonProperty("last_read")
  private Date lastRead;

  @JsonProperty("unread_messages")
  private Integer unreadMessages;

  @JsonProperty("user")
  private UserResponse user;

  @Nullable
  @JsonProperty("last_delivered_at")
  private Date lastDeliveredAt;

  @Nullable
  @JsonProperty("last_delivered_message_id")
  private String lastDeliveredMessageID;

  @Nullable
  @JsonProperty("last_read_message_id")
  private String lastReadMessageID;
}
