/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class RepliesMeta {

  @JsonProperty("depth_truncated")
  private Boolean depthTruncated;

  @JsonProperty("has_more")
  private Boolean hasMore;

  @JsonProperty("remaining")
  private Integer remaining;

  @Nullable
  @JsonProperty("next_cursor")
  private String nextCursor;
}
