/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class RuleBuilderRule {

  @JsonProperty("rule_type")
  private String ruleType;

  @Nullable
  @JsonProperty("cooldown_period")
  private String cooldownPeriod;

  @Nullable
  @JsonProperty("id")
  private String id;

  @Nullable
  @JsonProperty("logic")
  private String logic;

  @Nullable
  @JsonProperty("action_sequences")
  private List<CallRuleActionSequence> actionSequences;

  @Nullable
  @JsonProperty("conditions")
  private List<RuleBuilderCondition> conditions;

  @Nullable
  @JsonProperty("groups")
  private List<RuleBuilderConditionGroup> groups;

  @Nullable
  @JsonProperty("action")
  private RuleBuilderAction action;
}
