/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

/**
 * Check whether a target exists in a segment Check whether a target exists in a segment. Returns
 * 200 if the target exists, 404 otherwise
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
public class SegmentTargetExistsRequest {}
