/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class SessionClient {

  @Nullable
  @JsonProperty("ip")
  private String ip;

  @Nullable
  @JsonProperty("name")
  private String name;

  @Nullable
  @JsonProperty("network_type")
  private String networkType;

  @Nullable
  @JsonProperty("version")
  private String version;

  @Nullable
  @JsonProperty("location")
  private CallStatsLocation location;
}
