/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class SourceInterruption {

  @JsonProperty("at_offset_min")
  private Double atOffsetMin;

  @JsonProperty("dead_air_s")
  private Integer deadAirS;

  @JsonProperty("kind")
  private String kind;

  @Nullable
  @JsonProperty("seamless")
  private Boolean seamless;
}
