/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

/** Start closed captions Starts closed captions */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class StartClosedCaptionsRequest {

  @Nullable
  @JsonProperty("enable_transcription")
  private Boolean enableTranscription;

  @Nullable
  @JsonProperty("external_storage")
  private String externalStorage;

  @Nullable
  @JsonProperty("language")
  private String language;

  @Nullable
  @JsonProperty("speech_segment_config")
  private SpeechSegmentConfig speechSegmentConfig;
}
