/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

/** Stop frame recording Stops frame recording Sends events: - call.frame_recording_stopped */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
public class StopFrameRecordingRequest {}
