/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class Supporting {

  @JsonProperty("delivery_incident_windows")
  private List<Incident> deliveryIncidentWindows;

  @JsonProperty("edge_outlier_zones")
  private List<String> edgeOutlierZones;

  @JsonProperty("source_drop_windows")
  private List<TimeWindow> sourceDropWindows;
}
