/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class ThreadParticipant {

  @JsonProperty("app_pk")
  private Integer appPk;

  @JsonProperty("channel_cid")
  private String channelCid;

  @JsonProperty("created_at")
  private Instant createdAt;

  @JsonProperty("last_read_at")
  private Instant lastReadAt;

  @JsonProperty("custom")
  private Map<String, Object> custom;

  @Nullable
  @JsonProperty("last_thread_message_at")
  private Instant lastThreadMessageAt;

  @Nullable
  @JsonProperty("left_thread_at")
  private Instant leftThreadAt;

  @Nullable
  @JsonProperty("thread_id")
  private String threadID;

  @Nullable
  @JsonProperty("user_id")
  private String userID;

  @Nullable
  @JsonProperty("user")
  private UserResponse user;
}
