/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

/** Result of tracking a single metric event */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class TrackActivityMetricsEventResult {

  @JsonProperty("activity_id")
  private String activityID;

  @JsonProperty("allowed")
  private Boolean allowed;

  @JsonProperty("metric")
  private String metric;

  @Nullable
  @JsonProperty("error")
  private String error;
}
