/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class TranscriptionSettingsRequest {

  @Nullable
  @JsonProperty("closed_caption_mode")
  private String closedCaptionMode;

  @Nullable
  @JsonProperty("language")
  private String language;

  @Nullable
  @JsonProperty("mode")
  private String mode;

  @Nullable
  @JsonProperty("speech_segment_config")
  private SpeechSegmentConfig speechSegmentConfig;

  @Nullable
  @JsonProperty("translation")
  private TranslationSettings translation;
}
