/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.getstream.models.framework.RateLimit;
import java.util.Optional;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import io.getstream.annotations.Query;
/**
 * Unfollow a feed
 * Removes a follow and broadcasts FollowRemovedEvent
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor@lombok.AllArgsConstructor

public class UnfollowRequest {

@Query("delete_notification_activity")
           @JsonIgnore
           private Boolean DeleteNotificationActivity;
@Query("keep_history")
           @JsonIgnore
           private Boolean KeepHistory;
@Query("enrich_own_fields")
           @JsonIgnore
           private Boolean EnrichOwnFields;
}
