/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UpdateSIPInboundRoutingRuleRequest {

  @JsonProperty("name")
  private String name;

  @JsonProperty("called_numbers")
  private List<String> calledNumbers;

  @JsonProperty("trunk_ids")
  private List<String> trunkIds;

  @JsonProperty("caller_configs")
  private SIPCallerConfigsRequest callerConfigs;

  @Nullable
  @JsonProperty("caller_numbers")
  private List<String> callerNumbers;

  @Nullable
  @JsonProperty("call_configs")
  private SIPCallConfigsRequest callConfigs;

  @Nullable
  @JsonProperty("direct_routing_configs")
  private SIPDirectRoutingRuleCallConfigsRequest directRoutingConfigs;

  @Nullable
  @JsonProperty("pin_protection_configs")
  private SIPPinProtectionConfigsRequest pinProtectionConfigs;

  @Nullable
  @JsonProperty("pin_routing_configs")
  private SIPInboundRoutingRulePinConfigsRequest pinRoutingConfigs;
}
