/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.getstream.annotations.Query;
import java.util.Date;
import org.jetbrains.annotations.Nullable;

/**
 * Update live location Updates an existing live location with new coordinates or expiration time
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UpdateLiveLocationRequest {

  @JsonProperty("message_id")
  private String messageID;

  @Nullable
  @JsonProperty("end_at")
  private Date endAt;

  @Nullable
  @JsonProperty("latitude")
  private Double latitude;

  @Nullable
  @JsonProperty("longitude")
  private Double longitude;

  @Query("user_id")
  @JsonIgnore
  private String UserID;
}
