/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UpdateFollowRequest {

  @JsonProperty("source")
  private String source;

  @JsonProperty("target")
  private String target;

  @Nullable
  @JsonProperty("create_notification_activity")
  private Boolean createNotificationActivity;

  @Nullable
  @JsonProperty("follower_role")
  private String followerRole;

  @Nullable
  @JsonProperty("push_preference")
  private String pushPreference;

  @Nullable
  @JsonProperty("skip_push")
  private Boolean skipPush;

  @Nullable
  @JsonProperty("status")
  private String status;

  @Nullable
  @JsonProperty("custom")
  private Map<String, Object> custom;
}
