/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

/**
 * Upsert external storage Creates or updates the external storage configuration for the app.
 * Currently only AWS S3 (via cross-account IAM role assumption) is supported.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UpsertImporterExternalStorageRequest {

  @JsonProperty("type")
  private String type;

  @Nullable
  @JsonProperty("aws_s3")
  private UpsertExternalStorageAWSS3Request awsS3;
}
