/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UpsertPushPreferencesResponse {

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("user_channel_preferences")
  private Map<String, Map<String, ChannelPushPreferencesResponse>> userChannelPreferences;

  @JsonProperty("user_preferences")
  private Map<String, PushPreferencesResponse> userPreferences;
}
