/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UpsertActionConfigItem {

  @JsonProperty("action")
  private String action;

  @JsonProperty("entity_type")
  private String entityType;

  @JsonProperty("order")
  private Integer order;

  @Nullable
  @JsonProperty("description")
  private String description;

  @Nullable
  @JsonProperty("icon")
  private String icon;

  @Nullable
  @JsonProperty("id")
  private String id;

  @Nullable
  @JsonProperty("queue_type")
  private String queueType;

  @Nullable
  @JsonProperty("custom")
  private Map<String, Object> custom;
}
