/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The user&#39;s interest tags after the write, ordered by descending weight, then manually set
 * tags before computed ones, then descending count, then ascending tag name
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UpsertUserInterestsResponse {

  @JsonProperty("duration")
  private String duration;

  @JsonProperty("interests")
  private List<InterestTagResponse> interests;
}
