/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UserFlaggedEvent {

  @JsonProperty("created_at")
  private Instant createdAt;

  @JsonProperty("type")
  private String type;

  @Nullable
  @JsonProperty("target_user")
  private String targetUser;

  @Nullable
  @JsonProperty("target_users")
  private List<String> targetUsers;

  @Nullable
  @JsonProperty("user")
  private User user;
}
