/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class UserResponseCommonFields {

  @JsonProperty("banned")
  private Boolean banned;

  @JsonProperty("created_at")
  private Instant createdAt;

  @JsonProperty("id")
  private String id;

  @JsonProperty("language")
  private String language;

  @JsonProperty("online")
  private Boolean online;

  @JsonProperty("role")
  private String role;

  @JsonProperty("updated_at")
  private Instant updatedAt;

  @JsonProperty("blocked_user_ids")
  private List<String> blockedUserIds;

  @JsonProperty("teams")
  private List<String> teams;

  @JsonProperty("custom")
  private Map<String, Object> custom;

  @Nullable
  @JsonProperty("avg_response_time")
  private Integer avgResponseTime;

  @Nullable
  @JsonProperty("deactivated_at")
  private Instant deactivatedAt;

  @Nullable
  @JsonProperty("deleted_at")
  private Instant deletedAt;

  @Nullable
  @JsonProperty("image")
  private String image;

  @Nullable
  @JsonProperty("last_active")
  private Instant lastActive;

  @Nullable
  @JsonProperty("name")
  private String name;

  @Nullable
  @JsonProperty("revoke_tokens_issued_before")
  private Instant revokeTokensIssuedBefore;

  @Nullable
  @JsonProperty("teams_role")
  private Map<String, String> teamsRole;
}
