/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

/**
 * Query feed moderation templates Retrieve a list of feed moderation templates that define preset
 * moderation rules and configurations. Limited to 100 templates per request.
 */
@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
public class V2QueryTemplatesRequest {}
