/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class WebhookFailoverConfig {

  @Nullable
  @JsonProperty("gcs_bucket")
  private String gcsBucket;

  @Nullable
  @JsonProperty("gcs_credentials")
  private String gcsCredentials;

  @Nullable
  @JsonProperty("gcs_path")
  private String gcsPath;

  @Nullable
  @JsonProperty("s3_api_key")
  private String s3APIKey;

  @Nullable
  @JsonProperty("s3_bucket")
  private String s3Bucket;

  @Nullable
  @JsonProperty("s3_path")
  private String s3Path;

  @Nullable
  @JsonProperty("s3_region")
  private String s3Region;

  @Nullable
  @JsonProperty("s3_role_arn")
  private String s3RoleArn;

  @Nullable
  @JsonProperty("s3_secret")
  private String s3Secret;

  @Nullable
  @JsonProperty("type")
  private String type;
}
