// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

package io.getstream;

import static org.junit.jupiter.api.Assertions.*;

import java.nio.charset.StandardCharsets;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

public class WebhookTest {

  private static final String TEST_SECRET = "test-webhook-secret";
  private static final String TEST_BODY = "{\"type\":\"test.event\"}";

  private static String computeSignature(String body, String secret) throws Exception {
    Mac mac = Mac.getInstance("HmacSHA256");
    SecretKeySpec secretKey =
        new SecretKeySpec(secret.getBytes(StandardCharsets.UTF_8), "HmacSHA256");
    mac.init(secretKey);
    byte[] hash = mac.doFinal(body.getBytes(StandardCharsets.UTF_8));
    StringBuilder sb = new StringBuilder();
    for (byte b : hash) {
      sb.append(String.format("%02x", b));
    }
    return sb.toString();
  }

  @Test
  public void testVerifySignatureValid() throws Exception {
    String signature = computeSignature(TEST_BODY, TEST_SECRET);
    assertTrue(Webhook.verifySignature(TEST_BODY, signature, TEST_SECRET));
  }

  @Test
  public void testVerifySignatureWrongSignature() {
    assertFalse(Webhook.verifySignature(TEST_BODY, "invalidsignature", TEST_SECRET));
  }

  @Test
  public void testVerifySignatureTamperedBody() throws Exception {
    String signature = computeSignature(TEST_BODY, TEST_SECRET);
    assertFalse(Webhook.verifySignature("{\"type\":\"tampered\"}", signature, TEST_SECRET));
  }

  @Test
  public void testVerifySignatureWrongSecret() throws Exception {
    String signature = computeSignature(TEST_BODY, TEST_SECRET);
    assertFalse(Webhook.verifySignature(TEST_BODY, signature, "wrong-secret"));
  }

  @Test
  public void testVerifySignatureEmptySignature() {
    assertFalse(Webhook.verifySignature(TEST_BODY, "", TEST_SECRET));
  }

  @Test
  public void testGetEventTypeValid() {
    assertEquals("message.new", Webhook.getEventType("{\"type\":\"message.new\"}"));
  }

  @Test
  public void testGetEventTypeMissingField() {
    assertNull(Webhook.getEventType("{\"foo\":\"bar\"}"));
  }

  @Test
  public void testGetEventTypeInvalidJson() {
    assertNull(Webhook.getEventType("not json"));
  }

  @Test
  public void testGetEventTypeEmptyObject() {
    assertNull(Webhook.getEventType("{}"));
  }

  @ParameterizedTest
  @CsvSource({
    "*, CustomEvent",
    "appeal.accepted, AppealAcceptedEvent",
    "appeal.created, AppealCreatedEvent",
    "appeal.rejected, AppealRejectedEvent",
    "call.accepted, CallAcceptedEvent",
    "call.blocked_user, BlockedUserEvent",
    "call.closed_caption, ClosedCaptionEvent",
    "call.closed_captions_failed, CallClosedCaptionsFailedEvent",
    "call.closed_captions_started, CallClosedCaptionsStartedEvent",
    "call.closed_captions_stopped, CallClosedCaptionsStoppedEvent",
    "call.created, CallCreatedEvent",
    "call.deleted, CallDeletedEvent",
    "call.dtmf, CallDTMFEvent",
    "call.ended, CallEndedEvent",
    "call.frame_recording_failed, CallFrameRecordingFailedEvent",
    "call.frame_recording_ready, CallFrameRecordingFrameReadyEvent",
    "call.frame_recording_started, CallFrameRecordingStartedEvent",
    "call.frame_recording_stopped, CallFrameRecordingStoppedEvent",
    "call.hls_broadcasting_failed, CallHLSBroadcastingFailedEvent",
    "call.hls_broadcasting_started, CallHLSBroadcastingStartedEvent",
    "call.hls_broadcasting_stopped, CallHLSBroadcastingStoppedEvent",
    "call.kicked_user, KickedUserEvent",
    "call.live_started, CallLiveStartedEvent",
    "call.member_added, CallMemberAddedEvent",
    "call.member_removed, CallMemberRemovedEvent",
    "call.member_updated, CallMemberUpdatedEvent",
    "call.member_updated_permission, CallMemberUpdatedPermissionEvent",
    "call.missed, CallMissedEvent",
    "call.moderation_blur, CallModerationBlurEvent",
    "call.moderation_warning, CallModerationWarningEvent",
    "call.notification, CallNotificationEvent",
    "call.permission_request, PermissionRequestEvent",
    "call.permissions_updated, UpdatedCallPermissionsEvent",
    "call.reaction_new, CallReactionEvent",
    "call.recording_failed, CallRecordingFailedEvent",
    "call.recording_ready, CallRecordingReadyEvent",
    "call.recording_started, CallRecordingStartedEvent",
    "call.recording_stopped, CallRecordingStoppedEvent",
    "call.rejected, CallRejectedEvent",
    "call.ring, CallRingEvent",
    "call.rtmp_broadcast_failed, CallRtmpBroadcastFailedEvent",
    "call.rtmp_broadcast_started, CallRtmpBroadcastStartedEvent",
    "call.rtmp_broadcast_stopped, CallRtmpBroadcastStoppedEvent",
    "call.session_ended, CallSessionEndedEvent",
    "call.session_participant_count_updated, CallSessionParticipantCountsUpdatedEvent",
    "call.session_participant_joined, CallSessionParticipantJoinedEvent",
    "call.session_participant_left, CallSessionParticipantLeftEvent",
    "call.session_started, CallSessionStartedEvent",
    "call.stats_report_ready, CallStatsReportReadyEvent",
    "call.transcription_failed, CallTranscriptionFailedEvent",
    "call.transcription_ready, CallTranscriptionReadyEvent",
    "call.transcription_started, CallTranscriptionStartedEvent",
    "call.transcription_stopped, CallTranscriptionStoppedEvent",
    "call.unblocked_user, UnblockedUserEvent",
    "call.updated, CallUpdatedEvent",
    "call.user_feedback_submitted, CallUserFeedbackSubmittedEvent",
    "call.user_muted, CallUserMutedEvent",
    "campaign.completed, CampaignCompletedEvent",
    "campaign.started, CampaignStartedEvent",
    "channel.created, ChannelCreatedEvent",
    "channel.deleted, ChannelDeletedEvent",
    "channel.frozen, ChannelFrozenEvent",
    "channel.hidden, ChannelHiddenEvent",
    "channel.max_streak_changed, MaxStreakChangedEvent",
    "channel.muted, ChannelMutedEvent",
    "channel.truncated, ChannelTruncatedEvent",
    "channel.unfrozen, ChannelUnFrozenEvent",
    "channel.unmuted, ChannelUnmutedEvent",
    "channel.updated, ChannelUpdatedEvent",
    "channel.visible, ChannelVisibleEvent",
    "channel_batch_update.completed, ChannelBatchCompletedEvent",
    "channel_batch_update.started, ChannelBatchStartedEvent",
    "custom, CustomVideoEvent",
    "export.bulk_image_moderation.error, AsyncExportErrorEvent",
    "export.bulk_image_moderation.success, AsyncBulkImageModerationEvent",
    "export.channels.error, AsyncExportErrorEvent",
    "export.channels.success, AsyncExportChannelsEvent",
    "export.moderation_logs.error, AsyncExportErrorEvent",
    "export.moderation_logs.success, AsyncExportModerationLogsEvent",
    "export.users.error, AsyncExportErrorEvent",
    "export.users.success, AsyncExportUsersEvent",
    "feeds.activity.added, ActivityAddedEvent",
    "feeds.activity.deleted, ActivityDeletedEvent",
    "feeds.activity.feedback, ActivityFeedbackEvent",
    "feeds.activity.marked, ActivityMarkEvent",
    "feeds.activity.pinned, ActivityPinnedEvent",
    "feeds.activity.reaction.added, ActivityReactionAddedEvent",
    "feeds.activity.reaction.deleted, ActivityReactionDeletedEvent",
    "feeds.activity.reaction.updated, ActivityReactionUpdatedEvent",
    "feeds.activity.removed_from_feed, ActivityRemovedFromFeedEvent",
    "feeds.activity.restored, ActivityRestoredEvent",
    "feeds.activity.unpinned, ActivityUnpinnedEvent",
    "feeds.activity.updated, ActivityUpdatedEvent",
    "feeds.bookmark.added, BookmarkAddedEvent",
    "feeds.bookmark.deleted, BookmarkDeletedEvent",
    "feeds.bookmark.updated, BookmarkUpdatedEvent",
    "feeds.bookmark_folder.deleted, BookmarkFolderDeletedEvent",
    "feeds.bookmark_folder.updated, BookmarkFolderUpdatedEvent",
    "feeds.comment.added, CommentAddedEvent",
    "feeds.comment.deleted, CommentDeletedEvent",
    "feeds.comment.reaction.added, CommentReactionAddedEvent",
    "feeds.comment.reaction.deleted, CommentReactionDeletedEvent",
    "feeds.comment.reaction.updated, CommentReactionUpdatedEvent",
    "feeds.comment.updated, CommentUpdatedEvent",
    "feeds.feed.created, FeedCreatedEvent",
    "feeds.feed.deleted, FeedDeletedEvent",
    "feeds.feed.updated, FeedUpdatedEvent",
    "feeds.feed_group.changed, FeedGroupChangedEvent",
    "feeds.feed_group.deleted, FeedGroupDeletedEvent",
    "feeds.feed_member.added, FeedMemberAddedEvent",
    "feeds.feed_member.removed, FeedMemberRemovedEvent",
    "feeds.feed_member.updated, FeedMemberUpdatedEvent",
    "feeds.follow.created, FollowCreatedEvent",
    "feeds.follow.deleted, FollowDeletedEvent",
    "feeds.follow.updated, FollowUpdatedEvent",
    "feeds.notification_feed.updated, NotificationFeedUpdatedEvent",
    "feeds.stories_feed.updated, StoriesFeedUpdatedEvent",
    "flag.updated, FlagUpdatedEvent",
    "ingress.error, IngressErrorEvent",
    "ingress.started, IngressStartedEvent",
    "ingress.stopped, IngressStoppedEvent",
    "member.added, MemberAddedEvent",
    "member.removed, MemberRemovedEvent",
    "member.updated, MemberUpdatedEvent",
    "message.deleted, MessageDeletedEvent",
    "message.flagged, MessageFlaggedEvent",
    "message.new, MessageNewEvent",
    "message.pending, PendingMessageEvent",
    "message.read, MessageReadEvent",
    "message.unblocked, MessageUnblockedEvent",
    "message.undeleted, MessageUndeletedEvent",
    "message.updated, MessageUpdatedEvent",
    "moderation.custom_action, ModerationCustomActionEvent",
    "moderation.flagged, ModerationFlaggedEvent",
    "moderation.mark_reviewed, ModerationMarkReviewedEvent",
    "moderation_check.completed, ModerationCheckCompletedEvent",
    "moderation_rule.triggered, ModerationRulesTriggeredEvent",
    "notification.mark_unread, NotificationMarkUnreadEvent",
    "notification.reminder_due, ReminderNotificationEvent",
    "notification.thread_message_new, NotificationThreadMessageNewEvent",
    "reaction.deleted, ReactionDeletedEvent",
    "reaction.new, ReactionNewEvent",
    "reaction.updated, ReactionUpdatedEvent",
    "reminder.created, ReminderCreatedEvent",
    "reminder.deleted, ReminderDeletedEvent",
    "reminder.updated, ReminderUpdatedEvent",
    "review_queue_item.new, ReviewQueueItemNewEvent",
    "review_queue_item.updated, ReviewQueueItemUpdatedEvent",
    "thread.updated, ThreadUpdatedEvent",
    "user.banned, UserBannedEvent",
    "user.deactivated, UserDeactivatedEvent",
    "user.deleted, UserDeletedEvent",
    "user.flagged, UserFlaggedEvent",
    "user.messages.deleted, UserMessagesDeletedEvent",
    "user.muted, UserMutedEvent",
    "user.reactivated, UserReactivatedEvent",
    "user.unbanned, UserUnbannedEvent",
    "user.unmuted, UserUnmutedEvent",
    "user.unread_message_reminder, UserUnreadReminderEvent",
    "user.updated, UserUpdatedEvent",
  })
  public void testParseWebhookEvent(String eventType, String expectedClassName)
      throws Webhook.WebhookException {
    String payload = "{\"type\":\"" + eventType + "\"}";
    Object event = Webhook.parseWebhookEvent(payload);
    assertNotNull(event);
    assertEquals(expectedClassName, event.getClass().getSimpleName());
  }

  @Test
  public void testParseWebhookEventUnknownType() {
    assertThrows(
        Webhook.WebhookException.class,
        () -> {
          Webhook.parseWebhookEvent("{\"type\":\"unknown.event\"}");
        });
  }

  @Test
  public void testParseWebhookEventMissingType() {
    assertThrows(
        Webhook.WebhookException.class,
        () -> {
          Webhook.parseWebhookEvent("{\"foo\":\"bar\"}");
        });
  }

  @Test
  public void testParseWebhookEventInvalidJson() {
    assertThrows(
        Webhook.WebhookException.class,
        () -> {
          Webhook.parseWebhookEvent("not json");
        });
  }
}
