/*
 * ========================================================================
 * WARNING: GENERATED CODE -- DO NOT EDIT!
 * ========================================================================
 *
 * This file was auto-generated by GetStream internal OpenAPI
 *
 * Any modifications to this file will be lost upon regeneration.
 * To make changes, please modify the source templates and regenerate.
 *
 * ========================================================================
 */
package io.getstream.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import org.jetbrains.annotations.Nullable;

@lombok.Data
@lombok.Builder
@lombok.NoArgsConstructor
@lombok.AllArgsConstructor
public class SendReactionRequest {

  @JsonProperty("reaction")
  private ReactionRequest reaction;

  @Nullable
  @JsonProperty("enforce_unique")
  private Boolean enforceUnique;

  @Nullable
  @JsonProperty("skip_push")
  private Boolean skipPush;
}
