name: Build

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
